# Page settings
baseurl = "localhost:1313"
title = "Web3 Research Lab"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Prof. Dr. Dr. Momtaz"
  description = "TUM Web3 Research Lab"
  email = "karin.papavlassopoulos(at)tum.de"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Web3 Research Lab"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "TUM Web3 Research Lab"
    subtitle = 'We bundle Germanyâ€™s most productive blockchain researchers and provide teaching, talent sourcing, and advisory for students, companies, and policymakers, respectively.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "momtaz.webp"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."


    [[params.testimonials.item]]
      quote = "&ldquo;With the Web3 Research Lab, Munich now hosts a European powerhouse to advance education and research in web3. I look forward to a flourishing web3 ecosystem in Munich.&rdquo;"
      person = 'Dr. David An, Partner Dracoon Ventures https://www.linkedin.com/in/davidan'
      img = "person1.jpg"
      alt = "Dr. David An"

    [[params.testimonials.item]]
      quote = "&ldquo;Prof. Momtaz and his team are doing globally leading research on blockchain in business with high practical relevance. It is great that the Web3 Research Lab provides an institutional platform to bridge academia and practice.&rdquo;"
      person = 'Paul Kammerer, CCO www.fincite.de'
      img = "person1.jpg"
      alt = "Paul Kammerer"

    [[params.testimonials.item]]
      quote = "&ldquo;We are proud to have the Web3 Research Lab at TUM as our primary partner for the MunichX accelerator. They are going to play a pivotal role in helping us fostering Munich's Web3 ecosystem by supporting the most promising founders of tomorrow.&rdquo;"
      person = 'Simon Dedic, Partner www.moonrockcapital.io'
      img = "person1.jpg"
      alt = "Simon Dedic"

    [[params.testimonials.item]]
      quote = "&ldquo; PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER  PLACEHOLDER .&rdquo;"
      person = 'Florian Peter, VP https://greenfield.bnbchain.org'
      img = "person3.jpg"
      alt = "Florian Peter"

    [[params.testimonials.item]]
      quote = "&ldquo;As an alum of TUM, I'm thrilled to see the TUM Web3 Research Lab driving innovation and education in the blockchain realm. TUM breeds great blockchain minds. bitsCrunch is delighted that the Web3 Research Lab is consolidating educational initiatives within and beyond the TUM ecosystem.&rdquo;"
      person = 'Vijay Pravin, CEO https://bitscrunch.com/'
      img = "person1.jpg"
      alt = "Vijay Pravin"
    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Prof. Dr. Dr. Paul P. Momtaz"
      position = "Professor of Entrepreneurial Finance at TUM"
      description = ""
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", ""],
        ["icon-facebook", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/paulmomtaz/"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "S3deployment"
URL = "s3://web3rl?region=eu-central-1"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
